server:
  port: 8086      #端口号

spring:
  application:
    name: admin-service    #服务名
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://10.1.12.77:10081/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 10.1.12.225
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

#自定义内容
sc:
  jwt:
    secret: sc@Login(Auth}*^31)&czxy% # 登录校验的密钥
    pubKeyPath: D:/rsa/rsa.pub      # 公钥地址
    priKeyPath: D:/rsa/rsa.pri      # 私钥地址
    expire: 30 # 过期时间,单位分钟


web-service:
  ribbon:
    listOfServers: http://10.1.12.184:8081

