package com.zl.dc.mapper;

import com.zl.dc.pojo.FundCollectionRecordDO;

public interface FundCollectionRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_collection_record
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    int deleteByPrimaryKey(Integer planRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_collection_record
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    int insert(FundCollectionRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_collection_record
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    int insertSelective(FundCollectionRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_collection_record
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    FundCollectionRecordDO selectByPrimaryKey(Integer planRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_collection_record
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    int updateByPrimaryKeySelective(FundCollectionRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_collection_record
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    int updateByPrimaryKey(FundCollectionRecordDO record);
}