package com.zl.dc.mapper;

public interface OtherBankCardDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int deleteByPrimaryKey(Integer bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int insert(OtherBankCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int insertSelective(OtherBankCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    OtherBankCardDO selectByPrimaryKey(Integer bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int updateByPrimaryKeySelective(OtherBankCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int updateByPrimaryKey(OtherBankCardDO record);
}