package com.zl.dc.mapper;

import com.zl.dc.pojo.OtherBankCard;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OtherBankCardDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int deleteByPrimaryKey(Integer bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int insert(OtherBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int insertSelective(OtherBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    OtherBankCard selectByPrimaryKey(Integer bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int updateByPrimaryKeySelective(OtherBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int updateByPrimaryKey(OtherBankCard record);
}