package com.zl.dc.mapper;

import com.zl.dc.pojo.OtherBankCard;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OtherBankCardDOMapper {

    /**
     * @author: Redsheep
     * @Param bankCardId 银行卡id
     * @param userId 用户id
     * @return: Integer 银行卡id
     * @description:
     * @data: 2019/8/15 19:31
     */
    Integer selectByOtherBankCardIdAndPassword(Integer otherBankCardId, Integer userId);


    /**
    * @author: Redsheep
    * @Param Integer 他行卡id
    * @return: Integer 影响条数
    * @description:
    * @data: 2019/8/15 17:54
    */
    Integer deleteByOtherBankCardId(Integer otherBankCardId);

    /**
    * @author: Redsheep
    * @Param Integer 用户id
    * @return: List<OtherBankCard> 用户的他行卡
    * @description: 根据用户的id查询所有的他行卡
    * @data: 2019/8/15 17:53
    */
    List<OtherBankCard> selectOtherBankCardList(Integer userId);

    /**
    * @author: Redsheep
    * @Param otherBankCard
    * @return: Integer 返回id
    * @description:
    * @data: 2019/8/15 11:53
    */
    Integer selectByUserIdAndCardNumber(OtherBankCard otherBankCard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int deleteByPrimaryKey(Integer bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int insert(OtherBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int insertSelective(OtherBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    OtherBankCard selectByPrimaryKey(Integer bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int updateByPrimaryKeySelective(OtherBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_bank_card
     *
     * @mbg.generated Wed Aug 14 11:28:09 CST 2019
     */
    int updateByPrimaryKey(OtherBankCard record);
}