package com.zl.dc.mapper;

import com.zl.dc.pojo.transferRecordDO;

public interface transferRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    int deleteByPrimaryKey(Integer transferRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    int insert(transferRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    int insertSelective(transferRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    transferRecordDO selectByPrimaryKey(Integer transferRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    int updateByPrimaryKeySelective(transferRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_record
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    int updateByPrimaryKey(transferRecordDO record);
}