server:
  port: 10010

spring:
  application:
    name: api-web-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10081/eureka
  instance:
    prefer-ip-address: true

zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
    auth-service: /auth/**
    admin-service: /admin/**
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
sc:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
  filter:
    allowPaths:
      - /loginBySendSms #根据验证码登录(用户)
      - /getLogin #登录(管理员)
      - /GetUserList  #查询用户数量(管理员)
      - /GetRecords #查询记录数(管理员)
      - /GetAbnormals #查询异常数(管理员)
      - /sendSms  #发送短信(用户登录)
      - /login #用户登录(手机号/身份证号)
      - /getTransferRecords #查询所有订单(管理员)
      - /getBankUserList #管理员查询所有用户(带条件)
      - /memberStart #启用用户状态(管理员)
      - /memberStop #停用用户状态(管理员)
      - /GetUserByRedis #从redis查询用户信息
      - /updatePasswordSms  #修改密码----获取验证码
      - /updatePasswordVerify  #修改密码----验证验证码是否正确
      - /updateBankUserPassword    #修改密码----修改密码
      - /updatePhoneSms      #修改手机----获取验证码
      - /updatePhoneVerify   #修改手机----验证验证码是否正确