server:
  port: 10010

spring:
  application:
    name: web-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.1.12.77:10081/eureka
  instance:
    prefer-ip-address: true

zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
    auth-service: /auth/**
    admin-service: /admin/**
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
sc:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
  filter:
    allowPaths:
      # 管理员
      - /getLogin                 # 登录(管理员)
      - /GetUserList              # 查询用户数量(管理员)
      - /GetRecords               # 查询记录数(管理员)
      - /GetAbnormals             # 查询异常数(管理员)
      - /getTransferRecords       # 查询所有订单(管理员)
      - /getBankUserList          # 管理员查询所有用户(带条件)
      - /memberStart              # 启用用户状态(管理员)
      - /memberStop               # 停用用户状态(管理员)
      - /loginOut                 # 退出(管理员)
      - /getManagerTranscations   # 查询用户申请中的提卡信息(管理员)
      - /adopt                    # 提升卡种通过(管理员)
      - /NoPassage                # 提升卡种不通过(管理员)
      # 登录
      - /loginBySendSms           # 根据验证码登录(用户)
      - /sendSms                  # 发送短信(用户登录)
      - /login                    # 用户登录(手机号/身份证号)
      - /GetUserByRedis           # 从redis查询用户信息
      # 注册
      - /registrySms             #注册----获取验证码
      - /registry                #注册----注册
      # 个人中心
      - /updatePasswordSms        # 修改密码----获取验证码
      - /updatePasswordVerify     # 修改密码----验证验证码是否正确
      - /updateBankUserPassword   # 修改密码----修改密码
      - /updatePhoneSms           # 修改手机----获取验证码
      - /updatePhoneVerify        # 修改手机----验证验证码是否正确
      - /updatePhone              # 修改手机----修改手机
      # 转账
      - /getAllSubordinateBank    # 单次转账----查询出所有所属银行
      - /verifyBankCardForVo      # 单次转账----转账方法
      # 跨境转账
      - /getExchangeRate          # 跨境转账----根据用户选择的币种查询对应的汇率
      - /getExchangeRatePrice     # 跨境转账----根据人民币查询对饮外币
      - /getBankCardByUser        # 跨境转账----根据用户查询用户所持有的本行卡
      - /getExchangeRateCNY       # 跨境转账----根据外币查询对应人民币
      - /CrossBorderTransfer      # 跨境转账----转账
      # 转账记录
      - /getTransferRecordList    # 查询转账记录----根据月份和银行卡id
      - /getBankCardByUserId      # 根据用户id查询所有本行银行卡
      - /getBankCardBybankCardId  #根据银行卡ID查询银行卡
      - /sendUpgradeCard          #升级银行卡(发短信)
      - /UpgradeCard              #升级银行卡(申请)