server:
  port: 10010

spring:
  application:
    name: api-web-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10081/eureka
  instance:
    prefer-ip-address: true

zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
    auth-service: /auth/**
    admin-service: /admin/**
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 100
  ReadTimeout: 600
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
sc:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
  filter:
    allowPaths:
      - /loginBySendSms #根据验证码登录(用户)
      - /getLogin #登录(管理员)
      - /GetUserList  #查询用户数量
      - /GetRecords #查询记录数
      - /GetAbnormals #查询异常数
      - /sendSms  #发送短信(用户登录)
      - /login #用户登录(手机号/身份证号)
