server:
  port: 10010

spring:
  application:
    name: web-gateway
  servlet:
    multipart:
      max-file-size: 2MB
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.1.12.77:10081/eureka
  instance:
    prefer-ip-address: true

zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
    auth-service: /auth/**
    admin-service: /admin/**
  sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
sc:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
  filter:
    allowPaths:
      # 管理员
      - /getLogin                 # 登录(管理员)
      - /selectBankUserAll        # 查询用户数量(管理员)
      - /selectTransferRecordAll  # 查询记录数(管理员)
      - /selectManagerTranscationAll # 查询异常数(管理员)
      - /getTransferRecords       # 查询所有订单(管理员)
      - /getBankUserList          # 管理员查询所有用户(带条件)
      - /memberStart              # 启用用户状态(管理员)
      - /memberStop               # 停用用户状态(管理员)
      - /loginOut                 # 退出(管理员)
      - /getManagerTranscations   # 查询用户申请中的提卡信息(管理员)
      - /adopt                    # 提升卡种通过(管理员)
      - /NoPassage                # 提升卡种不通过(管理员)
      # 登录
      - /loginBySendSms           # 根据验证码登录(用户)
      - /sendSms                  # 发送短信(用户登录)
      - /login                    # 用户登录(手机号/身份证号)
      - /GetUserByRedis           # 从redis查询用户信息
      - /logout                   # 退出登录
      # 注册
      - /registrySms              # 注册----获取验证码
      - /registry                 # 注册----注册
      # 个人中心
      - /updatePasswordSms        # 修改密码----获取验证码
      - /updatePasswordVerify     # 修改密码----验证验证码是否正确
      - /updateBankUserPassword   # 修改密码----修改密码
      - /updatePhoneSms           # 修改手机----获取验证码
      - /updatePhoneVerify        # 修改手机----验证验证码是否正确
      - /updatePhone              # 修改手机----修改手机
      - /verifiedIdentity         # 实名认证
      # 转账
      - /getAllSubordinateBank    # 单次转账----查询出所有所属银行
      - /verifyBankCardForVo      # 单次转账----转账方法
      # 跨境转账
      - /getExchangeRate          # 跨境转账----根据用户选择的币种查询对应的汇率
      - /getExchangeRatePrice     # 跨境转账----根据人民币查询对饮外币
      - /getBankCardByUser        # 跨境转账----根据用户查询用户所持有的本行卡
      - /getExchangeRateCNY       # 跨境转账----根据外币查询对应人民币
      - /CrossBorderTransfer      # 跨境转账----转账
      # 转账记录
      - /getTransferRecordList    # 查询转账记录----根据月份和银行卡id
      # 本行卡
      - /getBankCardByUserId      # 根据用户id查询所有本行银行卡
      - /getBankCardBybankCardId  # 根据银行卡ID查询银行卡
      - /reportBankCardLoss       # 根据银行卡id挂失本行卡
      # 升级银行卡
      - /getBankCardBybankCardId  #根据银行卡ID查询银行卡
      - /sendUpgradeCard          # 升级银行卡(发短信)
       # 收款群组
      - /selectPayeeGroupByUid    # 根据用户id返回用户所有的用户群组
      - /selectPayeeById          # 根据群组id返回所有的收款人
      - /addPayeeGroup            # 添加一条收款群组
      - /deletePayeeById          # 根据id删除群组用户
      - /addPayee                 # 根据VO添加群组收款人
      - /getBankCardBybankCardId  # 根据银行卡ID查询银行卡
      #升级银行卡
      - /sendUpgradeCard          # 升级银行卡(发短信)
      - /sendUpgradeCard          # 升级银行卡(发短信)
      - /UpgradeCard              # 升级银行卡(申请)
      # 他行卡
      - /addOtherBankCard         # 绑定他行卡
      - /untiedOtherBankCard      # 解绑他行卡
      - /getOtherBankCardByUserId # 根据用户id获取他行卡
      - /findBankCardIdentification # 根据银行卡号查标识符
      - /deleteOtherBankCard      # 解绑他行卡
      - /getBankCardBybankCardId  # 根据银行卡ID查询银行卡
      - /getOtherBankCardByUserId # 根据用户id获取他行卡
      # 批量转账
      - /submitTransferBulk       # 批量转账提交
      #企业
      - /bankEnterpriseLogin      # 企业用户登录
      - /batchImport              # 批量导入收款人
      - /enterpriseTransfer       # 企业转账
      - /enterpriseLogout         # 企业退出登录
      #消息中心
      - /getMessageCenter         # 根据用户id查询待付款单和升级卡记录
      - /agreeGathering           # 用户通知付款
      - /updateManagerTranscationStatus    # 用户主动取消升级卡申请
      - /getBankCardByUser        # 根据用户id查询用户名下所有银行卡
      #主动收款
      - /getActiveCollection      # 查询所有主动收款历史订单
      - /updateGatheringType      # 用户取消主动收款
      - /addTransactionTecord     # 发起新的主动收款(添加交易订单)
      #消息通知
      - /MessageNotification      # 根据登录用户id查询消息
      - /setRedisMessage          # 将消息存到redis5天
      # 资金归集
      - /getFundCollectionPlanList # 根据用户id所有的归集计划
      - /addFundCollectionPlan    # 添加归集计划
      - /shutdownFundCollectionPlan   # 手动终止一个归集计划
      - /getFundCollectionRecordList  # 查看某个归集计划的记录
