package com.zl.dc.pojo;

import java.util.Date;

public class FundCollectionRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_collection_record.plan_record_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    private Integer planRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_collection_record.plan_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    private Integer planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_collection_record.record_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_collection_record.gmt_create
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fund_collection_record.gmt_modified
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_collection_record.plan_record_id
     *
     * @return the value of fund_collection_record.plan_record_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public Integer getPlanRecordId() {
        return planRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_collection_record.plan_record_id
     *
     * @param planRecordId the value for fund_collection_record.plan_record_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public void setPlanRecordId(Integer planRecordId) {
        this.planRecordId = planRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_collection_record.plan_id
     *
     * @return the value of fund_collection_record.plan_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_collection_record.plan_id
     *
     * @param planId the value for fund_collection_record.plan_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_collection_record.record_id
     *
     * @return the value of fund_collection_record.record_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_collection_record.record_id
     *
     * @param recordId the value for fund_collection_record.record_id
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_collection_record.gmt_create
     *
     * @return the value of fund_collection_record.gmt_create
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_collection_record.gmt_create
     *
     * @param gmtCreate the value for fund_collection_record.gmt_create
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fund_collection_record.gmt_modified
     *
     * @return the value of fund_collection_record.gmt_modified
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fund_collection_record.gmt_modified
     *
     * @param gmtModified the value for fund_collection_record.gmt_modified
     *
     * @mbg.generated Sat Aug 17 17:45:26 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}