package com.zl.dc.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class transferRecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_id
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Integer transferRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_uuid
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private String transferRecordUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_amount
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private BigDecimal transferRecordAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_record_time
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Date transferRecordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_note
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private String transferNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_status
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Byte transferStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.transfer_type
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Byte transferType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.user_id
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.bank_out_card
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private String bankOutCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.in_card_user_name
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private String inCardUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.bank_in_identification
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private String bankInIdentification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.bank_in_card
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private String bankInCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.gmt_create
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_record.gmt_modified
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_id
     *
     * @return the value of transfer_record.transfer_record_id
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Integer getTransferRecordId() {
        return transferRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_id
     *
     * @param transferRecordId the value for transfer_record.transfer_record_id
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferRecordId(Integer transferRecordId) {
        this.transferRecordId = transferRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_uuid
     *
     * @return the value of transfer_record.transfer_record_uuid
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public String getTransferRecordUuid() {
        return transferRecordUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_uuid
     *
     * @param transferRecordUuid the value for transfer_record.transfer_record_uuid
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferRecordUuid(String transferRecordUuid) {
        this.transferRecordUuid = transferRecordUuid == null ? null : transferRecordUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_amount
     *
     * @return the value of transfer_record.transfer_record_amount
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public BigDecimal getTransferRecordAmount() {
        return transferRecordAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_amount
     *
     * @param transferRecordAmount the value for transfer_record.transfer_record_amount
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferRecordAmount(BigDecimal transferRecordAmount) {
        this.transferRecordAmount = transferRecordAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_record_time
     *
     * @return the value of transfer_record.transfer_record_time
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Date getTransferRecordTime() {
        return transferRecordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_record_time
     *
     * @param transferRecordTime the value for transfer_record.transfer_record_time
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferRecordTime(Date transferRecordTime) {
        this.transferRecordTime = transferRecordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_note
     *
     * @return the value of transfer_record.transfer_note
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public String getTransferNote() {
        return transferNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_note
     *
     * @param transferNote the value for transfer_record.transfer_note
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferNote(String transferNote) {
        this.transferNote = transferNote == null ? null : transferNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_status
     *
     * @return the value of transfer_record.transfer_status
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Byte getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_status
     *
     * @param transferStatus the value for transfer_record.transfer_status
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferStatus(Byte transferStatus) {
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.transfer_type
     *
     * @return the value of transfer_record.transfer_type
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Byte getTransferType() {
        return transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.transfer_type
     *
     * @param transferType the value for transfer_record.transfer_type
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setTransferType(Byte transferType) {
        this.transferType = transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.user_id
     *
     * @return the value of transfer_record.user_id
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.user_id
     *
     * @param userId the value for transfer_record.user_id
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.bank_out_card
     *
     * @return the value of transfer_record.bank_out_card
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public String getBankOutCard() {
        return bankOutCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.bank_out_card
     *
     * @param bankOutCard the value for transfer_record.bank_out_card
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setBankOutCard(String bankOutCard) {
        this.bankOutCard = bankOutCard == null ? null : bankOutCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.in_card_user_name
     *
     * @return the value of transfer_record.in_card_user_name
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public String getInCardUserName() {
        return inCardUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.in_card_user_name
     *
     * @param inCardUserName the value for transfer_record.in_card_user_name
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setInCardUserName(String inCardUserName) {
        this.inCardUserName = inCardUserName == null ? null : inCardUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.bank_in_identification
     *
     * @return the value of transfer_record.bank_in_identification
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public String getBankInIdentification() {
        return bankInIdentification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.bank_in_identification
     *
     * @param bankInIdentification the value for transfer_record.bank_in_identification
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setBankInIdentification(String bankInIdentification) {
        this.bankInIdentification = bankInIdentification == null ? null : bankInIdentification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.bank_in_card
     *
     * @return the value of transfer_record.bank_in_card
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public String getBankInCard() {
        return bankInCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.bank_in_card
     *
     * @param bankInCard the value for transfer_record.bank_in_card
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setBankInCard(String bankInCard) {
        this.bankInCard = bankInCard == null ? null : bankInCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.gmt_create
     *
     * @return the value of transfer_record.gmt_create
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.gmt_create
     *
     * @param gmtCreate the value for transfer_record.gmt_create
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_record.gmt_modified
     *
     * @return the value of transfer_record.gmt_modified
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_record.gmt_modified
     *
     * @param gmtModified the value for transfer_record.gmt_modified
     *
     * @mbg.generated Tue Aug 13 09:12:09 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}